# Generated by Django 5.0.2 on 2024-02-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_schedule_date_schedule_date_assigned_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeassignment',
            table='employee_assignment',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shift',
        ),
    ]
