# Generated by Django 5.0.2 on 2024-03-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employeeassignment_table_alter_schedule_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Rota',
        ),
        migrations.AlterModelTable(
            name='rota',
            table='rota',
        ),
    ]
