# Generated by Django 5.0.2 on 2024-04-09 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_schedule_rota_alter_rota_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
