# Generated by Django 5.0.2 on 2024-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
